
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.AchievementConfig
{
public sealed partial class AchievementInfo : Luban.BeanBase
{
    public AchievementInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);StageInfos = new System.Collections.Generic.List<AchievementConfig.StageInfo>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { AchievementConfig.StageInfo _e0;  _e0 = global::cfg.AchievementConfig.StageInfo.DeserializeStageInfo(_buf); StageInfos.Add(_e0);}}
        Clamp01 = _buf.ReadBool();
        LocalizationKey = _buf.ReadString();
    }

    public static AchievementInfo DeserializeAchievementInfo(ByteBuf _buf)
    {
        return new AchievementConfig.AchievementInfo(_buf);
    }

    /// <summary>
    /// 注释行
    /// </summary>
    public readonly int Id;
    public readonly System.Collections.Generic.List<AchievementConfig.StageInfo> StageInfos;
    /// <summary>
    /// 进度是否显示为01
    /// </summary>
    public readonly bool Clamp01;
    /// <summary>
    /// 多语言对应Key值
    /// </summary>
    public readonly string LocalizationKey;
   
    public const int __ID__ = -803001440;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in StageInfos) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "StageInfos:" + Luban.StringUtil.CollectionToString(StageInfos) + ","
        + "Clamp01:" + Clamp01 + ","
        + "LocalizationKey:" + LocalizationKey + ","
        + "}";
    }
}
}

