
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.AchievementConfig
{
/// <summary>
/// 成就某一阶段的完成条件和奖励
/// </summary>
public sealed partial class StageInfo : Luban.BeanBase
{
    public StageInfo(ByteBuf _buf) 
    {
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Conditions = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Conditions.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Rewards = new System.Collections.Generic.List<GlobalData.RewardItem>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { GlobalData.RewardItem _e0;  _e0 = global::cfg.GlobalData.RewardItem.DeserializeRewardItem(_buf); Rewards.Add(_e0);}}
    }

    public static StageInfo DeserializeStageInfo(ByteBuf _buf)
    {
        return new AchievementConfig.StageInfo(_buf);
    }

    /// <summary>
    /// 阶段完成条件
    /// </summary>
    public readonly System.Collections.Generic.List<int> Conditions;
    /// <summary>
    /// 阶段奖励
    /// </summary>
    public readonly System.Collections.Generic.List<GlobalData.RewardItem> Rewards;
   
    public const int __ID__ = 1258862127;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Rewards) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "conditions:" + Luban.StringUtil.CollectionToString(Conditions) + ","
        + "rewards:" + Luban.StringUtil.CollectionToString(Rewards) + ","
        + "}";
    }
}
}

