
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.AchievementConfig
{
public partial class TbAchievementInfo
{
    private readonly System.Collections.Generic.Dictionary<int, AchievementConfig.AchievementInfo> _dataMap;
    private readonly System.Collections.Generic.List<AchievementConfig.AchievementInfo> _dataList;
    
    public TbAchievementInfo(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, AchievementConfig.AchievementInfo>();
        _dataList = new System.Collections.Generic.List<AchievementConfig.AchievementInfo>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            AchievementConfig.AchievementInfo _v;
            _v = global::cfg.AchievementConfig.AchievementInfo.DeserializeAchievementInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, AchievementConfig.AchievementInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<AchievementConfig.AchievementInfo> DataList => _dataList;

    public AchievementConfig.AchievementInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public AchievementConfig.AchievementInfo Get(int key) => _dataMap[key];
    public AchievementConfig.AchievementInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

