
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Cysharp.Threading.Tasks;
using Luban;

namespace cfg
{
public partial class Tables
{
    public AchievementConfig.TbAchievementInfo TbAchievementInfo {get; private set;}
    public LevelConfig.TbLevelInfo TbLevelInfo {get; private set;}
    
    private Tables()
    {
    }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbAchievementInfo = new AchievementConfig.TbAchievementInfo(loader("achievementconfig_tbachievementinfo"));
        TbLevelInfo = new LevelConfig.TbLevelInfo(loader("levelconfig_tblevelinfo"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbAchievementInfo.ResolveRef(this);
        TbLevelInfo.ResolveRef(this);
    }
	
	private async UniTask Initialize(System.Func<string, UniTask<ByteBuf>> loader)
	{
        TbAchievementInfo = new AchievementConfig.TbAchievementInfo(await loader("achievementconfig_tbachievementinfo"));
        TbLevelInfo = new LevelConfig.TbLevelInfo(await loader("levelconfig_tblevelinfo"));
        ResolveRef();
    }
    
    public static async UniTask<Tables> Create(System.Func<string, UniTask<ByteBuf>> loader)
    {
        var instance = new Tables();
        await instance.Initialize(loader);
        return instance;
    }
}

}
