
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.LevelConfig
{
public sealed partial class LevelInfo : Luban.BeanBase
{
    public LevelInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        LevelId = _buf.ReadString();
    }

    public static LevelInfo DeserializeLevelInfo(ByteBuf _buf)
    {
        return new LevelConfig.LevelInfo(_buf);
    }

    /// <summary>
    /// 注释行
    /// </summary>
    public readonly int Id;
    public readonly string LevelId;
   
    public const int __ID__ = -1600322038;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "LevelId:" + LevelId + ","
        + "}";
    }
}
}

