
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.GlobalData
{
/// <summary>
/// 奖励
/// </summary>
public sealed partial class RewardItem : Luban.BeanBase
{
    public RewardItem(ByteBuf _buf) 
    {
        Type = (GlobalData.RewardType)_buf.ReadInt();
        Num = _buf.ReadInt();
    }

    public static RewardItem DeserializeRewardItem(ByteBuf _buf)
    {
        return new GlobalData.RewardItem(_buf);
    }

    /// <summary>
    /// 奖励类型
    /// </summary>
    public readonly GlobalData.RewardType Type;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Num;
   
    public const int __ID__ = 1795519875;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "type:" + Type + ","
        + "num:" + Num + ","
        + "}";
    }
}
}

